//
//  LoginViewController.swift
//  swag
//
//  Created ahmetkardesseven on 22.12.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {

	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
